name: schedule_api
description: A Dart API Client for the Schedule API.
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.4.0
  intl: ^0.17.0

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.16.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec